### ISSUE TITLE
'process-es6' is not in the npm registry.

### ISSUE THREAD

**Issue by lw604217818** [calvinmetcalf/rollup-plugin-node-globals#10]
Hello!

 when I npm i :

npm ERR! code E404
npm ERR! 404 no such package available : process-es6
npm ERR! 404
npm ERR! 404  'process-es6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'rollup-plugin-node-globals'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wenba/.npm/_logs/2017-12-04T08_27_47_034Z-debug.log

**Comment by calvinmetcalf** [comment]
[yes it is](https://www.npmjs.com/package/process-es6), are you maybe off line or hooked up to some weird other registry ?
