### ISSUE TITLE
Error on __dirname

### ISSUE THREAD

**Issue by kuraga** [calvinmetcalf/rollup-plugin-node-globals#18]
```
(node:12505) UnhandledPromiseRejectionWarning: Error: Could not load node-globals:dirname (imported by /home/sasha/rotorjs/node_modules/tman/lib/tman.js): Path must be a string without null bytes
    at /home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:21724:19
    at <anonymous>
```

Any thoughts?

**Comment by calvinmetcalf** [comment]
how are you using this  ?

**Comment by kuraga** [comment]
@calvinmetcalf `tman` [does](https://github.com/thunks/tman/blob/925216e0084d1d4cce3595cd611c385ab6e17e05/lib/tman.js#L65)

**Comment by calvinmetcalf** [comment]
is it being included in your rollup configs ?

**Comment by kuraga** [comment]
@calvinmetcalf what do you mean?

Error disappears since I remove `__dirname` from that line.

**Comment by calvinmetcalf** [comment]
this is a plugin for rollup, depending on your config when building your thing it may or may not be included in your build and thus error out

**Comment by kuraga** [comment]
_UPDATED:_

@calvinmetcalf , 
[rollup-node-globals-issue.zip](https://github.com/calvinmetcalf/rollup-plugin-node-globals/files/2495523/rollup-node-globals-issue.zip),
`node build.js`.

**Comment by calvinmetcalf** [comment]
put globals before resolve in your config

**Comment by kuraga** [comment]
@calvinmetcalf , then:
```
Error: 'default' is not exported by node_modules/tman/lib/tman.js
    at error (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:13361:9)
    at handleMissingExport (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:13048:21)
    at Module.traceVariable (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:13469:17)
    at ModuleScope.findVariable (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:12723:29)
    at MemberExpression$$1.bind (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:11244:50)
    at CallExpression.NodeBase.bind (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:9183:23)
    at CallExpression.bind (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:10234:31)
    at ExpressionStatement$$1.NodeBase.bind (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:9183:23)
    at Program.NodeBase.bind (/home/sasha/rotorjs/node_modules/rollup/dist/rollup.js:9179:31)
```
But it [does](https://github.com/thunks/tman/blob/master/lib/tman.js#L16)...

**Comment by kuraga** [comment]
@calvinmetcalf Hm, interesting facts (on original code):

1. If code is `import tman as tman; tman.run();` - we have an error.
2. If code is `import tman as tman; tman.run();` and we remove `__dirname` [here](https://github.com/thunks/tman/blob/925216e0084d1d4cce3595cd611c385ab6e17e05/lib/tman.js#L65), - we don't have an error.
3. If code is `import tman as tman;` - we still have `__dirname` (and it's assignment) in the bundle but don't have an error!

**Comment by kuraga** [comment]
@calvinmetcalf  but what does this error mean? Where does it come from? The error. Forget the context.

**Comment by calvinmetcalf** [comment]
the original error has to do with it not being able to find the stand in module we use for __dirname, not sure why...

**Comment by kuraga** [comment]
@calvinmetcalf :smile: 

One option:
```js
try {
  // We wait one exception here...
  some_action();
  // ...but get another
} catch {  // well, we're waiting the concrete error. no others! point this? no, why!
  // Print message about error we're waitibg...
  // ...without others in mind
}
```

**Comment by kuraga** [comment]
@calvinmetcalf , got part of this issue.

1. Original:
  a. Plugins order: `resolve`, `commonjs`, `globals` (and `builtins`)
  b. ECMAScript modules? Yes.
  c. Result: `Error: Could not load node-globals:dirname (imported by /home/sasha/rotorjs/node_modules/tman/lib/tman.js): Path must be a string without null bytes`.

2. Trying A:
  a. Plugins order: `globals` (and `builtins`), `resolve`, `commonjs`.
  b. ECMAScript modules? Yes.
  c. Result: `Error: 'default' is not exported by node_modules/tman/lib/tman.js`.

3. Trying B:
  a. Plugins order: `globals` (and `builtins`), `resolve`, `commonjs`.
  b. **ECMAScript modules? No (building `script.js` instead of `script.mjs`, see [here](https://github.com/calvinmetcalf/rollup-plugin-node-globals/issues/18#issuecomment-427369212)).**
  c. Result: success!

4. Trying C:
  a. Plugins order: `resolve`, `commonjs`.
  b. ECMAScript modules? Yes.
  c. Result: no errors but unresolved symbols.

So, you [were right](https://github.com/calvinmetcalf/rollup-plugin-node-globals/issues/18#issuecomment-427377011):
> put globals before resolve in your config

But this plugins order is incompatible (in my code) with ESM... And ESM works fine without your plugin.

**Comment by kuraga** [comment]
@calvinmetcalf ahaha, I got it!!! We have a new error since I set correct plugins order. See #20 , please!

**Comment by kuraga** [comment]
Null byte (`\0`) is really in [these lines](https://github.com/calvinmetcalf/rollup-plugin-node-globals/blob/v1.4.0/src/index.js#L10-L11). It was introduced in #3 .

**Comment by kuraga** [comment]
Ah, ok, close in favor of #23 .
