### ISSUE TITLE
Is messing up with the npm global package

### ISSUE THREAD

**Issue by binarykitchen** [calvinmetcalf/rollup-plugin-node-globals#8]
In my project some other libs are requiring this package
https://github.com/Raynos/global

and it seems to conflict with yours. I think cannot use both. Otherwise I am seeing those errors

```
'default' is not exported by 'node_modules/global/document.js'
```

and cannot fix them with the namedExports option of the commonjs plugin.

**Comment by calvinmetcalf** [comment]
yeah I think this one is intercepting all imports of 'global' so I need to namespace it

**Comment by calvinmetcalf** [comment]
wait no we use the path so hm, do you have a small example that shows the behavior ?

**Comment by binarykitchen** [comment]
@calvinmetcalf it is this one WIP branch https://github.com/binarykitchen/videomail-client/tree/feature/rollupjs @calvinmetcalf

**Comment by calvinmetcalf** [comment]
why are you using both this library and globals if it's just on the browser then you shouldn't need that other library

**Comment by binarykitchen** [comment]
@calvinmetcalf hmm, sorry i dont follow you. to what other library are you referring you? are you saying i have one library too much when it comes to global stuff?

**Comment by calvinmetcalf** [comment]
possibly, I don't understand why you are using this plugin and https://github.com/Raynos/global

**Comment by binarykitchen** [comment]
@calvinmetcalf problem is that https://github.com/Raynos/global is a nested dependency of another dependency. not listing it directly in my package.json

and when i remove https://github.com/Raynos/global, then i am back to square one and see the same error i reported in your other repo:

```
99% (181): src/wrappers/optionsWrapper.js⚠️   'default' is not exported by 'node_modules/buffer-es6/index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/michael-heuberger/code/videomail-client/node_modules/buffer-es6/index.js (1:137)
1: import * as index from "/home/michael-heuberger/code/videomail-client/node_modules/buffer-es6/index.js"; export default ( index && index['default'] ) || index;
```

confusing ...

**Comment by binarykitchen** [comment]
ping?

**Comment by calvinmetcalf** [comment]
something is trying to do `import Buffer from 'buffer-es6'` instead of `import {Buffer} from 'buffer-es6'` its probably some nested dependency which is doing something like `var buffer = require('buffer');  var Buffer = buffer.Buffer;` or something weird like that.

**Comment by binarykitchen** [comment]
yep, that's my guess too - what should I do in your opinion @calvinmetcalf ?

**Comment by calvinmetcalf** [comment]
as I mentioned in the other thread you might want to switch to webpack or browserify, rollup is much more focused on bundling libs with less of a focus on making sure all your dependencies work

**Comment by binarykitchen** [comment]
i see - wish rollup's website has this advice written somewhere in form of a light warning ... this did cost me hours for nothing :(
